### ISSUE TITLE
Signer type missing the generated type definition file in 1.0.2

### ISSUE THREAD

**Issue by betterclever** [persistenceOne/persistenceJS#42]
https://github.com/persistenceOne/persistenceJS/pull/38

As we added the signer field here without any type,  there’s a weird issue happening.
In the typescript type definitions that get generated when using this library, the signer field is missing entirely.

This is the definition there
```
static init(mnemonic: string, chainConfig?: Config): Promise<PersistenceClient>;
```
whereas, in the the compiled js target it expects signer field mandatorily. So in the usage of the library in other scripts, the chainConfig is treated as a signer and the chainConfig is available as undefined to the compiled js target which is causing for library to misbehave.

**Comment by vishrutsingh** [comment]
@betterclever getting it fixed in the next pr
